README.md

added contributor list to readme

---

muffnn/base.py
muffnn/mlp_classifier.py
muffnn/mlp_regressor.py
muffnn/tests/test_mlp_classifier.py
muffnn/tests/test_mlp_regressor.py

As part of this I did a little minor refactoring:
* simplified some of the logic around batch sizes in the `fit` (now `partial_fit`) method.
* made a `_is_fitted` property to simplify checking the `_fitted` state
* extracted a `_check_inputs` function to make `fit` (now `partial_fit`) a bit more readable.
* renamed `_init_model` to `_set_up_graph` for clarity.
TODO

added partial_fit functionality

---

muffnn/autoencoder/autoencoder.py

I missed a bit of comment cleanup in the bigger PR.
Closes #10

DOC updated comments to match code in autoencoder

---

muffnn/mlp/base.py
muffnn/mlp/tests/test_base.py

fix initialization of random state in MLP partial_fit

---

CHANGELOG.md
muffnn/version.py

Preparing for making a release.

update changelog and bump version to 0.2.0

---

muffnn/mlp/mlp_classifier.py

BUG make sure label encoder is pickled properly

---

Dockerfile
environment.yml
muffnn/core.py
muffnn/tests/test_tfbase.py

This PR updates to the latest tensorflow and fixes some changes to saving mechanism.

ENH update to latest tensorflow 0.12.1

---

muffnn/mlp/mlp_classifier.py

Adding score function for mlp_classifier

Fix Issue #26

---

muffnn/mlp/base.py
muffnn/mlp/mlp_classifier.py
muffnn/mlp/mlp_regressor.py
muffnn/mlp/tests/test_base.py

This PR adds the ability to set the SGD solver and its settings for the MLP.
Closes #37

ENH added solver settings for the MLP

---

CHANGELOG.md
muffnn/version.py

PROD release v1.1.0

---

muffnn/mlp/base.py
muffnn/mlp/mlp_classifier.py
muffnn/mlp/mlp_regressor.py

Documentation change proposed in the Deep Learning room.
@mheilman @beckermr

documentation change explaining dropout with sparse inputs

---

CHANGELOG.md
muffnn/mlp/tests/test_mlp_classifier.py
muffnn/version.py
setup.py

This PR updates the code for v1.1.2.
Closes #48

PROD release 1.1.2

---

CHANGELOG.md
circle.yml
environment.yml
muffnn/fm/tests/test_fm_classifier.py
muffnn/mlp/tests/test_mlp_classifier.py
setup.py

This PR updates the dependencies.

PROD update the deps

---

CHANGELOG.md
muffnn/version.py

This PR releases version 1.2.0.

PROD release v1.2.0

---

CHANGELOG.md
muffnn/version.py

This PR updates the code to v2.0.0 for a pip release. 
To do:
Closes #73

PROD update to v2.0.0 for pip release

---

CHANGELOG.md
CONTRIBUTING.md
muffnn/version.py

This also updates a couple outdated references to pyflakes since travis uses flake8 now.

bump version to 2.1.0

---

README.rst

This adds a few basic badges to the GitHub README.

add a few badges to the README

---

CHANGELOG.md
muffnn/__init__.py

This adds `__version__` in the top-level `__init__.py` to follow packaging norms.

add __version__ to top-level package

---

CHANGELOG.md

Of course, I remember to add a changelog message *right after* merging. Related to #84

added changelog message for prediction gradient

---

CHANGELOG.md
muffnn/fm/fm_classifier.py
muffnn/fm/tests/test_fm_classifier.py

BUG fixed bug in FMClassifier for predicting one sample

---

CHANGELOG.md
muffnn/mlp/base.py
muffnn/mlp/mlp_classifier.py
muffnn/mlp/mlp_regressor.py
muffnn/mlp/tests/test_mlp_classifier.py
muffnn/mlp/tests/test_mlp_regressor.py
requirements.txt
setup.py

This PR adds support for alpha dropout and SELU activations.

ENH add support for alpha dropout and SELU

---

muffnn/__init__.py
muffnn/fm/fm_regressor.py
muffnn/fm/tests/test_fm_regressor.py

82eafc3 has all the relevant changes from the `FMClassifier`.

ENH FMRegressor

---

examples/mlp_prediction_gradient_digits.ipynb

add example notebook for prediction gradients

---

CHANGELOG.md
muffnn/mlp/base.py
muffnn/mlp/tests/test_base.py
muffnn/version.py

This PR has updates for the v2.2.0 release. I will tag it once the PR is merged.

ENH updates for v2.2.0

---

.travis.yml
CHANGELOG.md
README.rst
muffnn/__init__.py
muffnn/version.py
requirements.txt
setup.py

* Allows latest scikit-learn versions
* Bumps version to 2.3.0

[PARO-735] Allow latest scikit-learn; bump version to 2.3.0
