- muffnn/base.py
- muffnn/tests/test_tfbase.py
- muffnn/tfbase.py
This PR adds a base pickling class for TensorFlow scikit-learn style estimators. It abstracts out all of the core functionality that could conceivably (right now) be shared by say a MLP and an autoencoder, for example.
Closes #5
> REF add a base TF pickling class

- muffnn/mlp/base.py
- muffnn/mlp/mlp_classifier.py
- muffnn/mlp/tests/test_base.py
- muffnn/mlp/tests/test_mlp_classifier.py
This adds some PRs from the original private version of this code that didn't make it into the public version, by my mistake.
The changes are originally from @waltaskew.
* adds a monitor keyword argument to the MLP (e.g., for optional logging, checkpointing, early stopping)
* refactors the MLP sparse input to make it more efficient
* fixes multilabel classification
> In which we add functionality that was previously added in the private repo but was mistakenly not included in the public version

- muffnn/autoencoder/autoencoder.py
- muffnn/autoencoder/tests/test_autoencoder.py
- muffnn/mlp/base.py
- muffnn/mlp/mlp_classifier.py
- muffnn/mlp/mlp_regressor.py
- muffnn/mlp/tests/test_base.py
- muffnn/mlp/tests/test_mlp_classifier.py
- muffnn/mlp/tests/test_mlp_regressor.py
closes #6 (applies to both the MLP and autoencoder).
This changes the `dropout` keyword argument to `keep_prob` to be consistent internally and consistent with tensorflow.
> made dropout keep_prob keyword arg consistent with tensorflow

- muffnn/autoencoder/autoencoder.py
- muffnn/autoencoder/tests/test_autoencoder.py
This PR adds the ability to use relu activations for the autoencoder.
Changes in the tests include 
1. now use `relu` for the activation
2. renamed a bunch of them
3. changed the size of the hidden layers from 1 unit to 2 in many cases
4. made sure learning rates were set properly to get good results
Closes #21
> ENH add ability to use relu to autoencoder

- Dockerfile
- environment.yml
- muffnn/autoencoder/autoencoder.py
- muffnn/mlp/base.py
- muffnn/mlp/mlp_classifier.py
- muffnn/mlp/tests/test_base.py
This PR moves us to TF 1.0. 
See this page for upgrade instructions https://www.tensorflow.org/install/migration.
I have run the code through their upgrade script and not found any errors. 
Closes #29
> ENH upgrade to Tf 1.0

- CHANGELOG.md
- README.md
- environment.yml
- muffnn/version.py
Due to backwards incompatible changes in TensorFlow, it makes sense to bump the major version here to 1.0.0. I updated the docs to reflect the easier install procedure. Once this PR is merged, I will tag 1.0.0 and then push a new version to pypi.
> MAINT bump version to 1.0.0

- CHANGELOG.md
- MANIFEST.in
- muffnn/version.py
This PR fixes the packaging bug and bumps the version to `v1.1.1`.
Closes #41
> BUG add `MANIFEST.in` to fix packaging bug

- CHANGELOG.md
- muffnn/mlp/base.py
- muffnn/mlp/mlp_classifier.py
- muffnn/mlp/mlp_regressor.py
- muffnn/mlp/tests/test_base.py
Closes #42 
One issue is that one has to generate the grid search parameters themselves for this to work. So if you want to grid search over the learning rate and something else, you will need to explicitly list all of the combinations of the two options IIUIC.
The "scikit" way would be to list each arg explicitly with a suitable default. However this approach has serious maintenance and definitional issues. @mheilman, your proposed solution seems like a good middle ground.
> BUG make solver keyword args a dict so we can grid search over it

- CHANGELOG.md
- muffnn/mlp/mlp_classifier.py
- muffnn/mlp/tests/test_mlp_classifier.py
We are using the OvR multilabel conventions for scikit. In this case, the `classes_` attribute needs to be an array of length the number of labels.
> BUG make sure classes attribute for multilabel problems is set properly

- muffnn/__init__.py
- muffnn/fm/fm_classifier.py
- muffnn/fm/tests/test_fm_classifier.py
This PR adds a factorization machine classifier.
I am going to leave the regressor for another PR.
> ENH Factorization Machine classifier

- CHANGELOG.md
- muffnn/fm/fm_classifier.py
This PR hides an import from tf.contrib to make the import of the package faster. 
This is related to https://github.com/tensorflow/tensorflow/issues/11829.
Closes #55
> BUG hide import from tf.contrib to make overall imports faster

- muffnn/autoencoder/autoencoder.py
- muffnn/autoencoder/tests/test_autoencoder.py
This PR adds the monitor keyword to the autoencoder. 
Closes #20
> ENH add monitor keyword to the autoencoder

- requirements.txt
This PR updates the requirements file to properly match python 2.7.
See here https://www.python.org/dev/peps/pep-0496/#examples
> BUG update requirements to properly match python 2

- CHANGELOG.md
- muffnn/mlp/base.py
- muffnn/mlp/mlp_classifier.py
- muffnn/mlp/mlp_regressor.py
- muffnn/mlp/tests/test_base.py
- muffnn/mlp/tests/test_mlp_classifier.py
- muffnn/mlp/tests/test_mlp_regressor.py
This PR moves the MLP to an xavier init. 
Closes #64
> ENH add xavier init to MLP

- AUTHORS.md
- README.md
This PR updates the readme.
Closes #61
> DOC Update README.md

- CHANGELOG.md
- muffnn/mlp/base.py
- muffnn/mlp/mlp_classifier.py
- muffnn/mlp/mlp_regressor.py
- muffnn/mlp/tests/test_base.py
- muffnn/mlp/tests/test_mlp_classifier.py
- muffnn/mlp/tests/test_mlp_regressor.py
- muffnn/mlp/tests/util.py
- support sample weights in MLPClassifier
- support sample weights in MLPRegressor
- add tests ensuring sample weights are handled reasonably
@mheilman
> In Which We Add Support for Sample Weights to MLPs

- muffnn/mlp/base.py
- muffnn/mlp/tests/test_mlp_classifier.py
- muffnn/mlp/tests/test_mlp_regressor.py
This adds a method to facilitate the interpretation of MLP model predictions.  Specifically, it enables one to compute the gradient of the final output layer (pre-sigmoid logits for logistic regression, etc.) with respect to the input features.
I'm leaving sparse inputs to a future PR.  Also, I have some notebooks illustrating the method on toy datasets that might be worth adding.
> add prediction_gradient method for MLPs

- CHANGELOG.md
- muffnn/fm/fm_classifier.py
- muffnn/mlp/mlp_classifier.py
A very minor thing: we were printing `y` instead of `target_type` when raising an exception about the type of `y`.
> Fixed ValueError for type of target in MLPClassifier

- .travis.yml
- CHANGELOG.md
- muffnn/autoencoder/tests/test_autoencoder.py
- muffnn/fm/tests/test_fm_classifier.py
- muffnn/fm/tests/test_fm_regressor.py
- muffnn/mlp/base.py
- muffnn/mlp/tests/test_mlp_classifier.py
- muffnn/mlp/tests/test_mlp_regressor.py
- requirements.txt
- setup.py
This PR increases the `tensorflow` version requirement to addresses the following security vulnerabilities in tensorflow: CVE-2018-7576, CVE-2018-7575, CVE-2019-9635, CVE-2018-7577, CVE-2018-10055, CVE-2018-7574. They are of severity: 1x CRITICAL, 3x HIGH, 2x MEDIUM. (From PR #97 .) Aside from increasing the required `tensorflow` version and adding Python 3.7 testing, the rest of this PR is all modifications to the testing code to get tests to pass. Failures seem to be due to changes in `scikit-learn`, `scipy`, and `flake8`.
> MAINT Update dependency versions

- .travis.yml
- CHANGELOG.md
- README.rst
- muffnn/autoencoder/autoencoder.py
- muffnn/autoencoder/tests/test_autoencoder.py
- muffnn/core.py
- muffnn/fm/fm_classifier.py
- muffnn/fm/fm_regressor.py
- muffnn/fm/tests/test_fm_classifier.py
- muffnn/fm/tests/test_fm_regressor.py
- muffnn/mlp/base.py
- muffnn/mlp/mlp_classifier.py
- muffnn/mlp/mlp_regressor.py
- muffnn/mlp/tests/test_base.py
- muffnn/mlp/tests/test_mlp_classifier.py
- muffnn/mlp/tests/test_mlp_regressor.py
- muffnn/tests/test_tfbase.py
- requirements.txt
- setup.py
This UNTESTED patch addresses the tensorflow vulns. 
--timball
> Update requirements.txt and setup.py according to GHSA-977j-xj7q-2jr9

- .travis.yml
- CHANGELOG.md
- README.rst
- requirements.txt
- setup.py
This updates the minimum TF version, per https://github.com/advisories/GHSA-4g9f-63rx-5cw4.
It also removes Python 3.5 support and sets more specific scikit-learn version requirements to avoid test failures and incompatibilities.
> update TF version, remove py3.5 support
